const defaultQrOptions = {
    outputFormat: "JSON",
    encoding: "Base64",
    genString: "@TLTFTBRTTTMTT1T2TPTCTTWWW",
    platform: "mobile"
}

const defaultFormFields = 'SLFB@iM12PCcb';

const standardFields = {
    'L': {
        name: "lastname",
        id: "lastname",
        required:true,
        autocomplete:"off",
        type: "text",
        maxlength: 50,
        label: "Nom (lastname)",
        class: "form-control",
        placeholder: "Last Name",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'F': {
        name: "firstname",
        required:true,
        autocomplete:"off",
        id: "firstname",
        type: "text",
        maxlength: 50,
        label: "Prénom (firstname)",
        class: "form-control",
        placeholder: "First Name",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'S': {
        name: "sex",
        required:true,
        autocomplete:"off",
        id: "sex",
        type: "select",
        label: "Sexe (sex)",
        options: {
            male: 'Homme (male)',
            female: 'Femme (female)'
        },
        class: "form-select",
        placeholder: " ",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'B': {
        name: "birthdate",
        pattern: "\d{4}-\d{1,2}-\d{1,2}",
        required:true,
        autocomplete:"off",
        id: "birthdate",
        type: "text",
        label: "Date de naissance (Birthdate Year-Month-Day)",
        class: "form-control datepicker",
        placeholder: "Year-Month-Day",
        readonly: "readonly",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    '1': {
        name: "address1",
        required:true,
        autocomplete:"off",
        id: "address1",
        type: "text",
        maxlength: 50,
        label: "Adresse - ligne 1",
        class: "form-control",
        placeholder: "Address 1",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    '2': {
        name: "address2",
        id: "address2",
        type: "text",
        maxlength: 50,
        label: "Adresse - ligne 2",
        class: "form-control",
        placeholder: "Address 2 (Optional)",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'P': {
        name: "postcode",
        required:true,
        autocomplete:"off",
        id: "postcode",
        type: "text",
        maxlength: 20,
        label: "Code postal (postcode)",
        class: "form-control",
        placeholder: "ZIP Code",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    '@': {
        name: "email",
        required:true,
        autocomplete:"off",
        id: "email",
        type: "email",
        maxlength: 50,
        label: "Email",
        class: "form-control",
        placeholder: "Email",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'i': {
        name: "countrycode",
        id: "countrycode",
        type: "select",
        label: "Code pays (Country Code)",
        options: "countrycodes",
        class: "form-select",
        placeholder: " ",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
        
    },
    'M': {
        name: "mobile",
        required:true,
        autocomplete:"off",
        id: "mobile",
        type: "tel",
        maxlength: 15,
        label: "Téléphone Mobile (mobile number)",
        class: "form-control",
        placeholder: "0781112233",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'C': {
        name: "city",
        required:true,
        autocomplete:"off",
        id: "city",
        type: "text",
        maxlength: 50,
        label: "Ville (city)",
        class: "form-control",
        placeholder: "City",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'c': {
        name: "country",
        required:true,
        autocomplete:"off",
        id: "country",
        type: "select",
        label: "Pays (country)",
        options: "iso2country",
        class: "form-select",
        placeholder: "Country",
        label_classes: ["form-label"],
        div: true,
        div_classes: ["mb-3", "form-floating"]
    },
    'b' : {
        type: "button",
        id: "print-button",
        value: "Print/Imprimer",
        class: "btn btn-primary"
    }
}

const standardLists = {
    iso2country: {
        "CH": "Switzerland",
        "FR": "France",
        "IT": "Italy",
        "AT": "Austria",
        "AF": "Afghanistan",
        "AX": "Åland Islands",
        "AL": "Albania",
        "DZ": "Algeria",
        "AS": "American Samoa",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguilla",
        "AQ": "Antarctica",
        "AG": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia, Plurinational State of",
        "BQ": "Bonaire, Sint Eustatius and Saba",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BV": "Bouvet Island",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "BN": "Brunei Darussalam",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CV": "Cape Verde",
        "KY": "Cayman Islands",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CX": "Christmas Island",
        "CC": "Cocos (Keeling) Islands",
        "CO": "Colombia",
        "KM": "Comoros",
        "CG": "Congo",
        "CD": "Congo, the Democratic Republic of the",
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "CI": "Côte d'Ivoire",
        "HR": "Croatia",
        "CU": "Cuba",
        "CW": "Curaçao",
        "CY": "Cyprus",
        "CZ": "Czech Republic",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "ET": "Ethiopia",
        "FK": "Falkland Islands (Malvinas)",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "GF": "French Guiana",
        "PF": "French Polynesia",
        "TF": "French Southern Territories",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GD": "Grenada",
        "GP": "Guadeloupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GG": "Guernsey",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "HM": "Heard Island and McDonald Mcdonald Islands",
        "VA": "Holy See (Vatican City State)",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran, Islamic Republic of",
        "IQ": "Iraq",
        "IE": "Ireland",
        "IM": "Isle of Man",
        "IL": "Israel",
        "JM": "Jamaica",
        "JP": "Japan",
        "JE": "Jersey",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "KP": "Korea, Democratic People's Republic of",
        "KR": "Korea, Republic of",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Lao People's Democratic Republic",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MO": "Macao",
        "MK": "Macedonia, the Former Yugoslav Republic of",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "YT": "Mayotte",
        "MX": "Mexico",
        "FM": "Micronesia, Federated States of",
        "MD": "Moldova, Republic of",
        "MC": "Monaco",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Norfolk Island",
        "MP": "Northern Mariana Islands",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PS": "Palestine, State of",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PN": "Pitcairn",
        "PL": "Poland",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "RE": "Réunion",
        "RO": "Romania",
        "RU": "Russian Federation",
        "RW": "Rwanda",
        "BL": "Saint Barthélemy",
        "SH": "Saint Helena, Ascension and Tristan da Cunha",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "MF": "Saint Martin (French part)",
        "PM": "Saint Pierre and Miquelon",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SX": "Sint Maarten (Dutch part)",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "GS": "South Georgia and the South Sandwich Islands",
        "SS": "South Sudan",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SR": "Suriname",
        "SJ": "Svalbard and Jan Mayen",
        "SZ": "Swaziland",
        "SE": "Sweden",
        "SY": "Syrian Arab Republic",
        "TW": "Taiwan, Republic of China",
        "TJ": "Tajikistan",
        "TZ": "Tanzania, United Republic of",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TR": "Turkey",
        "TM": "Turkmenistan",
        "TC": "Turks and Caicos Islands",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom",
        "US": "United States",
        "UM": "United States Minor Outlying Islands",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VE": "Venezuela, Bolivarian Republic of",
        "VN": "Viet Nam",
        "VG": "Virgin Islands, British",
        "VI": "Virgin Islands, U.S.",
        "WF": "Wallis and Futuna",
        "EH": "Western Sahara",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe"
    },
    countrycodes: {
        "+41":"Switzerland(+41)",
        "+33":"France(+33)",

        "+93":"Afghanistan(+93)",
        "+355":"Albania(+355)",
        "+213":"Algeria(+213)",
        "+1-684":"American Samoa(+1-684)",
        "+376":"Andorra(+376)",
        "+244":"Angola(+244)",
        "+1-264":"Anguilla(+1-264)",
        "+672":"Antarctica(+672)",
        "+1-268":"Antigua(+1-268)",
        "+54":"Argentina(+54)",
        "+374":"Armenia(+374)",
        "+297":"Aruba(+297)",
        "+61":"Australia(+61)",
        "+43":"Austria(+43)",
        "+994":"Azerbaijan(+994)",
        "+1-242":"Bahamas(+1-242)",
        "+973":"Bahrain(+973)",
        "+880":"Bangladesh(+880)",
        "+1-246":"Barbados(+1-246)",
        "+375":"Belarus(+375)",
        "+32":"Belgium(+32)",
        "+501":"Belize(+501)",
        "+229":"Benin(+229)",
        "+1-441":"Bermuda(+1-441)",
        "+975":"Bhutan(+975)",
        "+591":"Bolivia(+591)",
        "+387":"Bosnia",
        "+267":"Botswana(+267)",
        "+55":"Brazil(+55)",
        "+673":"Brunei(+673)",
        "+359":"Bulgaria(+359)",
        "+226":"Burkina Faso(+226)",
        "+257":"Burundi(+257)",
        "+855":"Cambodia(+855)",
        "+237":"Cameroon(+237)",
        "+238":"Cape Verde(+238)",
        "+1-345":"Cayman Islands(+1-345)",
        "+236":"Central African Republic(+236)",
        "+235":"Chad(+235)",
        "+56":"Chile(+56)",
        "+86":"China(+86)",
        "+57":"Colombia(+57)",
        "+243":"Congo(+243)",
        "+242":"Congo(+242)",
        "+682":"Cook Islands(+682)",
        "+506":"Costa Rica(+506)",
        "+225":"Cote D'Ivoire(+225)",
        "+385":"Croatia(+385)",
        "+53":"Cuba(+53)",
        "+357":"Cyprus(+357)",
        "+420":"Czech Republic(+420)",
        "+45":"Denmark(+45)",
        "+253":"Djibouti(+253)",
        "+1-767":"Dominica(+1-767)",
        "+1-829  ":"Dominican Republic(+1-829)",
        "+670":"East Timor(+670)",
        "+593 ":"Ecuador(+593 )",
        "+20":"Egypt(+20)",
        "+503":"El Salvador(+503)",
        "+240":"Equatorial Guinea(+240)",
        "+291":"Eritrea(+291)",
        "+372":"Estonia(+372)",
        "+251":"Ethiopia(+251)",
        "+500":"Falkland Islands(+500)",
        "+298":"Faroe Islands(+298)",
        "+679":"Fiji(+679)",
        "+358":"Finland(+358)",
        "+594":"French Guyana(+594)",
        "+689":"French Polynesia(+689)",
        "+241":"Gabon(+241)",
        "+220":"Gambia(+220)",
        "+995":"Georgia(+995)",
        "+49":"Germany(+49)",
        "+233":"Ghana(+233)",
        "+350":"Gibraltar(+350)",
        "+30":"Greece(+30)",
        "+299":"Greenland(+299)",
        "+1-473":"Grenada(+1-473)",
        "+590":"Guadeloupe(+590)",
        "+1-671":"Guam(+1-671)",
        "+502":"Guatemala(+502)",
        "+224":"Guinea(+224)",
        "+245":"Guinea-Bissau(+245)",
        "+592":"Guyana(+592)",
        "+509":"Haiti(+509)",
        "+504":"Honduras(+504)",
        "+852":"Hong Kong(+852)",
        "+36":"Hungary(+36)",
        "+354":"Iceland(+354)",
        "+91":"India(+91)",
        "+62":"Indonesia(+62)",
        "+98":"Iran(+98)",
        "+964":"Iraq(+964)",
        "+353":"Ireland(+353)",
        "+972":"Israel(+972)",
        "+39":"Italy(+39)",
        "+1-876":"Jamaica(+1-876)",
        "+81":"Japan(+81)",
        "+962":"Jordan(+962)",
        "+254":"Kenya(+254)",
        "+686":"Kiribati(+686)",
        "+850":"North Korea(+850)",
        "+82":"South Korea(+82)",
        "+965":"Kuwait(+965)",
        "+996":"Kyrgyzstan(+996)",
        "+856":"Laos(+856)",
        "+371":"Latvia(+371)",
        "+961":"Lebanon(+961)",
        "+266":"Lesotho(+266)",
        "+231":"Liberia(+231)",
        "+218":"Libya(+218)",
        "+423":"Liechtenstein(+423)",
        "+370":"Lithuania(+370)",
        "+352":"Luxembourg(+352)",
        "+853":"Macau(+853)",
        "+389":"Macedonia(+389)",
        "+261":"Madagascar(+261)",
        "+265":"Malawi(+265)",
        "+60":"Malaysia(+60)",
        "+960":"Maldives(+960)",
        "+223":"Mali(+223)",
        "+356":"Malta(+356)",
        "+692":"Marshall Islands(+692)",
        "+596":"Martinique (French)(+596)",
        "+222":"Mauritania(+222)",
        "+230":"Mauritius(+230)",
        "+269":"Mayotte(+269)",
        "+52":"Mexico(+52)",
        "+691":"Micronesia(+691)",
        "+373":"Moldova(+373)",
        "+377":"Monaco(+377)",
        "+976":"Mongolia(+976)",
        "+1-664":"Montserrat(+1-664)",
        "+212":"Morocco(+212)",
        "+258":"Mozambique(+258)",
        "+95":"Myanmar(+95)",
        "+264":"Namibia(+264)",
        "+674":"Nauru(+674)",
        "+977":"Nepal(+977)",
        "+31":"Netherlands(+31)",
        "+599":"Netherlands Antilles(+599)",
        "+687":"New Caledonia(+687)",
        "+64":"New Zealand (Aotearoa)(+64)",
        "+505":"Nicaragua(+505)",
        "+227":"Niger(+227)",
        "+234":"Nigeria(+234)",
        "+683":"Niue(+683)",
        "+1-670":"Northern Mariana Islands(+1-670)",
        "+47":"Norway(+47)",
        "+968":"Oman(+968)",
        "+92":"Pakistan(+92)",
        "+680":"Palau(+680)",
        "+970":"Palestinian State(+970)",
        "+507":"Panama(+507)",
        "+675":"Papua New Guinea(+675)",
        "+595":"Paraguay(+595)",
        "+51":"Peru(+51)",
        "+63":"Philippines(+63)",
        "+48":"Poland(+48)",
        "+351":"Portugal(+351)",
        "+1-939":"Puerto Rico(+1-939)",
        "+974 ":"Qatar(+974)",
        "+262":"Reunion(+262)",
        "+40":"Romania(+40)",
        "+7":"Russian Federation(+7)",
        "+250":"Rwanda(+250)",
        "+290":"Saint Helena(+290)",
        "+1-869":"Saint Kitts and Nevis(+1-869)",
        "+1-758":"Saint Lucia(+1-758)",
        "+508":"Saint Pierre and Miquelon(+508)",
        "+1-784":"Saint Vincent and the Grenadines(+1-784)",
        "+685":"Samoa(+685)",
        "+378":"San Marino(+378)",
        "+239":"Sao Tome and Principe(+239)",
        "+966":"Saudi Arabia(+966)",
        "+381":"Serbia(+381)",
        "+221":"Senegal(+221)",
        "+248":"Seychelles(+248)",
        "+232":"Sierra Leone(+232)",
        "+65":"Singapore(+65)",
        "+421":"Slovakia(+421)",
        "+386":"Slovenia(+386)",
        "+677":"Solomon Islands(+677)",
        "+252":"Somalia(+252)",
        "+27":"South Africa(+27)",
        "+34":"Spain(+34)",
        "+94":"Sri Lanka(+94)",
        "+249":"Sudan(+249)",
        "+597":"Suriname(+597)",
        "+268":"Swaziland(+268)",
        "+46":"Sweden(+46)",
        "+963":"Syria(+963)",
        "+886":"Taiwan(+886)",
        "+992":"Tajikistan(+992)",
        "+255":"Tanzania(+255)",
        "+66":"Thailand(+66)",
        "+690":"Tokelau(+690)",
        "+676":"Tonga(+676)",
        "+1-868":"Trinidad/Tobago(+1-868)",
        "+216":"Tunisia(+216)",
        "+90":"Turkey(+90)",
        "+993":"Turkmenistan(+993)",
        "+1-649":"TurksCaicos Islands(+1-649)",
        "+688":"Tuvalu(+688)",
        "+256":"Uganda(+256)",
        "+380":"Ukraine(+380)",
        "+971":"United Arab Emirates(+971)",
        "+44":"United Kingdom",
        "+1":"United States/Canada(+1)",
        "+598":"Uruguay(+598)",
        "+998":"Uzbekistan(+998)",
        "+678":"Vanuatu(+678)",
        "+418":"Vatican City State(+418)",
        "+58":"Venezuela(+58)",
        "+84":"Vietnam(+84)",
        "+1-284":"Virgin Islands, UK(+1-284)",
        "+1-340":"Virgin Islands, US(+1-340)",
        "+681":"Wallis and Futuna(+681)",
        "+967":"Yemen(+967)",
        "+260":"Zambia(+260)",
        "+263":"Zimbabwe)(+263)"
    },
}

const standardConvertionTable = 
{
    "https?:\/\/.*m3-test\.ch.*": {
        dataLocations: { // Associate inputs with elemenents in formData.payload
            "input[autocomplete='firstname']": ["form", "firstname"],
            "input[autocomplete='lastname']": ["form", "lastname"],
            //"#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div:nth-child(4) > div:nth-child(1) > div:nth-child(5) > div.control.has-icons-left > div > div.react-datepicker-wrapper > div > input": ["form", "birthdate"],
            "div.react-datepicker-wrapper > div > input": ["form", "birthdate"],
            "input[autocomplete='email']": ["form", "email"],
            "input[autocomplete='phone']": ["form", "mobile"],
            "input[autocomplete='address line 1']": ["form", "address1"],
            "input[autocomplete='address line 2']": ["form", "address2"],
            "input[autocomplete='postal code']": ["form", "postcode"],
            "input[autocomplete='city']": ["form", "city"],
            "#root > div:nth-child(3) > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div > div:nth-child(2) > div:nth-child(6) > div.control.has-icons-left > div > select" : ["form", "country"],
            "#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div > div:nth-child(2) > div:nth-child(5) > div.control.has-icons-left > div > select": ["form", "country"],
            "input[id='maleRadio']": ["form", "sex"],
            "input[id='femaleRadio']": ["form", "sex"],
            //Le selecteur ci dessous est le selecteur countrycode du formulaire 
            "#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div > div:nth-child(1) > div > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select": ["form", "countrycode"],
            //Le selecteur ci dessous est le selecteur countrycode du formulaire normal de la page admin
            "#root > div > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div > div:nth-child(1) > div > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select" : ["form", "countrycode"]
        },
        dataTransforms: { // Modify the value of specified inputs based on below transformation tables
            "input[id='maleRadio']": {
                "male": true,
                "female": false
            },
            "input[id='femaleRadio']": {
                "male": false,
                "female": true
            },

            // Country, using reference to Standard Lists
            "#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div > div:nth-child(2) > div:nth-child(5) > div.control.has-icons-left > div > select": {
            "CH": "Switzerland",
            "FR": "France",
            "IT": "Italy",
            "AT": "Austria",
            "AF": "Afghanistan",
            "AX": "Åland Islands",
            "AL": "Albania",
            "DZ": "Algeria",
            "AS": "American Samoa",
            "AD": "Andorra",
            "AO": "Angola",
            "AI": "Anguilla",
            "AQ": "Antarctica",
            "AG": "Antigua and Barbuda",
            "AR": "Argentina",
            "AM": "Armenia",
            "AW": "Aruba",
            "AU": "Australia",
            "AZ": "Azerbaijan",
            "BS": "Bahamas",
            "BH": "Bahrain",
            "BD": "Bangladesh",
            "BB": "Barbados",
            "BY": "Belarus",
            "BE": "Belgium",
            "BZ": "Belize",
            "BJ": "Benin",
            "BM": "Bermuda",
            "BT": "Bhutan",
            "BO": "Bolivia, Plurinational State of",
            "BQ": "Bonaire, Sint Eustatius and Saba",
            "BA": "Bosnia and Herzegovina",
            "BW": "Botswana",
            "BV": "Bouvet Island",
            "BR": "Brazil",
            "IO": "British Indian Ocean Territory",
            "BN": "Brunei Darussalam",
            "BG": "Bulgaria",
            "BF": "Burkina Faso",
            "BI": "Burundi",
            "KH": "Cambodia",
            "CM": "Cameroon",
            "CA": "Canada",
            "CV": "Cape Verde",
            "KY": "Cayman Islands",
            "CF": "Central African Republic",
            "TD": "Chad",
            "CL": "Chile",
            "CN": "China",
            "CX": "Christmas Island",
            "CC": "Cocos (Keeling) Islands",
            "CO": "Colombia",
            "KM": "Comoros",
            "CG": "Congo",
            "CD": "Congo, the Democratic Republic of the",
            "CK": "Cook Islands",
            "CR": "Costa Rica",
            "CI": "Côte d'Ivoire",
            "HR": "Croatia",
            "CU": "Cuba",
            "CW": "Curaçao",
            "CY": "Cyprus",
            "CZ": "Czech Republic",
            "DK": "Denmark",
            "DJ": "Djibouti",
            "DM": "Dominica",
            "DO": "Dominican Republic",
            "EC": "Ecuador",
            "EG": "Egypt",
            "SV": "El Salvador",
            "GQ": "Equatorial Guinea",
            "ER": "Eritrea",
            "EE": "Estonia",
            "ET": "Ethiopia",
            "FK": "Falkland Islands (Malvinas)",
            "FO": "Faroe Islands",
            "FJ": "Fiji",
            "FI": "Finland",
            "GF": "French Guiana",
            "PF": "French Polynesia",
            "TF": "French Southern Territories",
            "GA": "Gabon",
            "GM": "Gambia",
            "GE": "Georgia",
            "DE": "Germany",
            "GH": "Ghana",
            "GI": "Gibraltar",
            "GR": "Greece",
            "GL": "Greenland",
            "GD": "Grenada",
            "GP": "Guadeloupe",
            "GU": "Guam",
            "GT": "Guatemala",
            "GG": "Guernsey",
            "GN": "Guinea",
            "GW": "Guinea-Bissau",
            "GY": "Guyana",
            "HT": "Haiti",
            "HM": "Heard Island and McDonald Mcdonald Islands",
            "VA": "Holy See (Vatican City State)",
            "HN": "Honduras",
            "HK": "Hong Kong",
            "HU": "Hungary",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IR": "Iran, Islamic Republic of",
            "IQ": "Iraq",
            "IE": "Ireland",
            "IM": "Isle of Man",
            "IL": "Israel",
            "JM": "Jamaica",
            "JP": "Japan",
            "JE": "Jersey",
            "JO": "Jordan",
            "KZ": "Kazakhstan",
            "KE": "Kenya",
            "KI": "Kiribati",
            "KP": "Korea, Democratic People's Republic of",
            "KR": "Korea, Republic of",
            "KW": "Kuwait",
            "KG": "Kyrgyzstan",
            "LA": "Lao People's Democratic Republic",
            "LV": "Latvia",
            "LB": "Lebanon",
            "LS": "Lesotho",
            "LR": "Liberia",
            "LY": "Libya",
            "LI": "Liechtenstein",
            "LT": "Lithuania",
            "LU": "Luxembourg",
            "MO": "Macao",
            "MK": "Macedonia, the Former Yugoslav Republic of",
            "MG": "Madagascar",
            "MW": "Malawi",
            "MY": "Malaysia",
            "MV": "Maldives",
            "ML": "Mali",
            "MT": "Malta",
            "MH": "Marshall Islands",
            "MQ": "Martinique",
            "MR": "Mauritania",
            "MU": "Mauritius",
            "YT": "Mayotte",
            "MX": "Mexico",
            "FM": "Micronesia, Federated States of",
            "MD": "Moldova, Republic of",
            "MC": "Monaco",
            "MN": "Mongolia",
            "ME": "Montenegro",
            "MS": "Montserrat",
            "MA": "Morocco",
            "MZ": "Mozambique",
            "MM": "Myanmar",
            "NA": "Namibia",
            "NR": "Nauru",
            "NP": "Nepal",
            "NL": "Netherlands",
            "NC": "New Caledonia",
            "NZ": "New Zealand",
            "NI": "Nicaragua",
            "NE": "Niger",
            "NG": "Nigeria",
            "NU": "Niue",
            "NF": "Norfolk Island",
            "MP": "Northern Mariana Islands",
            "NO": "Norway",
            "OM": "Oman",
            "PK": "Pakistan",
            "PW": "Palau",
            "PS": "Palestine, State of",
            "PA": "Panama",
            "PG": "Papua New Guinea",
            "PY": "Paraguay",
            "PE": "Peru",
            "PH": "Philippines",
            "PN": "Pitcairn",
            "PL": "Poland",
            "PT": "Portugal",
            "PR": "Puerto Rico",
            "QA": "Qatar",
            "RE": "Réunion",
            "RO": "Romania",
            "RU": "Russian Federation",
            "RW": "Rwanda",
            "BL": "Saint Barthélemy",
            "SH": "Saint Helena, Ascension and Tristan da Cunha",
            "KN": "Saint Kitts and Nevis",
            "LC": "Saint Lucia",
            "MF": "Saint Martin (French part)",
            "PM": "Saint Pierre and Miquelon",
            "VC": "Saint Vincent and the Grenadines",
            "WS": "Samoa",
            "SM": "San Marino",
            "ST": "Sao Tome and Principe",
            "SA": "Saudi Arabia",
            "SN": "Senegal",
            "RS": "Serbia",
            "SC": "Seychelles",
            "SL": "Sierra Leone",
            "SG": "Singapore",
            "SX": "Sint Maarten (Dutch part)",
            "SK": "Slovakia",
            "SI": "Slovenia",
            "SB": "Solomon Islands",
            "SO": "Somalia",
            "ZA": "South Africa",
            "GS": "South Georgia and the South Sandwich Islands",
            "SS": "South Sudan",
            "ES": "Spain",
            "LK": "Sri Lanka",
            "SD": "Sudan",
            "SR": "Suriname",
            "SJ": "Svalbard and Jan Mayen",
            "SZ": "Swaziland",
            "SE": "Sweden",
            "SY": "Syrian Arab Republic",
            "TW": "Taiwan, Province of China",
            "TJ": "Tajikistan",
            "TZ": "Tanzania, United Republic of",
            "TH": "Thailand",
            "TL": "Timor-Leste",
            "TG": "Togo",
            "TK": "Tokelau",
            "TO": "Tonga",
            "TT": "Trinidad and Tobago",
            "TN": "Tunisia",
            "TR": "Turkey",
            "TM": "Turkmenistan",
            "TC": "Turks and Caicos Islands",
            "TV": "Tuvalu",
            "UG": "Uganda",
            "UA": "Ukraine",
            "AE": "United Arab Emirates",
            "GB": "United Kingdom",
            "US": "United States",
            "UM": "United States Minor Outlying Islands",
            "UY": "Uruguay",
            "UZ": "Uzbekistan",
            "VU": "Vanuatu",
            "VE": "Venezuela, Bolivarian Republic of",
            "VN": "Viet Nam",
            "VG": "Virgin Islands, British",
            "VI": "Virgin Islands, U.S.",
            "WF": "Wallis and Futuna",
            "EH": "Western Sahara",
            "YE": "Yemen",
            "ZM": "Zambia",
            "ZW": "Zimbabwe"
        },
            "#root > div:nth-child(3) > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div > div:nth-child(2) > div:nth-child(6) > div.control.has-icons-left > div > select": {
                "CH": "Switzerland",
                "FR": "France",
                "IT": "Italy",
                "AT": "Austria",
                "AF": "Afghanistan",
                "AX": "Åland Islands",
                "AL": "Albania",
                "DZ": "Algeria",
                "AS": "American Samoa",
                "AD": "Andorra",
                "AO": "Angola",
                "AI": "Anguilla",
                "AQ": "Antarctica",
                "AG": "Antigua and Barbuda",
                "AR": "Argentina",
                "AM": "Armenia",
                "AW": "Aruba",
                "AU": "Australia",
                "AZ": "Azerbaijan",
                "BS": "Bahamas",
                "BH": "Bahrain",
                "BD": "Bangladesh",
                "BB": "Barbados",
                "BY": "Belarus",
                "BE": "Belgium",
                "BZ": "Belize",
                "BJ": "Benin",
                "BM": "Bermuda",
                "BT": "Bhutan",
                "BO": "Bolivia, Plurinational State of",
                "BQ": "Bonaire, Sint Eustatius and Saba",
                "BA": "Bosnia and Herzegovina",
                "BW": "Botswana",
                "BV": "Bouvet Island",
                "BR": "Brazil",
                "IO": "British Indian Ocean Territory",
                "BN": "Brunei Darussalam",
                "BG": "Bulgaria",
                "BF": "Burkina Faso",
                "BI": "Burundi",
                "KH": "Cambodia",
                "CM": "Cameroon",
                "CA": "Canada",
                "CV": "Cape Verde",
                "KY": "Cayman Islands",
                "CF": "Central African Republic",
                "TD": "Chad",
                "CL": "Chile",
                "CN": "China",
                "CX": "Christmas Island",
                "CC": "Cocos (Keeling) Islands",
                "CO": "Colombia",
                "KM": "Comoros",
                "CG": "Congo",
                "CD": "Congo, the Democratic Republic of the",
                "CK": "Cook Islands",
                "CR": "Costa Rica",
                "CI": "Côte d'Ivoire",
                "HR": "Croatia",
                "CU": "Cuba",
                "CW": "Curaçao",
                "CY": "Cyprus",
                "CZ": "Czech Republic",
                "DK": "Denmark",
                "DJ": "Djibouti",
                "DM": "Dominica",
                "DO": "Dominican Republic",
                "EC": "Ecuador",
                "EG": "Egypt",
                "SV": "El Salvador",
                "GQ": "Equatorial Guinea",
                "ER": "Eritrea",
                "EE": "Estonia",
                "ET": "Ethiopia",
                "FK": "Falkland Islands (Malvinas)",
                "FO": "Faroe Islands",
                "FJ": "Fiji",
                "FI": "Finland",
                "GF": "French Guiana",
                "PF": "French Polynesia",
                "TF": "French Southern Territories",
                "GA": "Gabon",
                "GM": "Gambia",
                "GE": "Georgia",
                "DE": "Germany",
                "GH": "Ghana",
                "GI": "Gibraltar",
                "GR": "Greece",
                "GL": "Greenland",
                "GD": "Grenada",
                "GP": "Guadeloupe",
                "GU": "Guam",
                "GT": "Guatemala",
                "GG": "Guernsey",
                "GN": "Guinea",
                "GW": "Guinea-Bissau",
                "GY": "Guyana",
                "HT": "Haiti",
                "HM": "Heard Island and McDonald Mcdonald Islands",
                "VA": "Holy See (Vatican City State)",
                "HN": "Honduras",
                "HK": "Hong Kong",
                "HU": "Hungary",
                "IS": "Iceland",
                "IN": "India",
                "ID": "Indonesia",
                "IR": "Iran, Islamic Republic of",
                "IQ": "Iraq",
                "IE": "Ireland",
                "IM": "Isle of Man",
                "IL": "Israel",
                "JM": "Jamaica",
                "JP": "Japan",
                "JE": "Jersey",
                "JO": "Jordan",
                "KZ": "Kazakhstan",
                "KE": "Kenya",
                "KI": "Kiribati",
                "KP": "Korea, Democratic People's Republic of",
                "KR": "Korea, Republic of",
                "KW": "Kuwait",
                "KG": "Kyrgyzstan",
                "LA": "Lao People's Democratic Republic",
                "LV": "Latvia",
                "LB": "Lebanon",
                "LS": "Lesotho",
                "LR": "Liberia",
                "LY": "Libya",
                "LI": "Liechtenstein",
                "LT": "Lithuania",
                "LU": "Luxembourg",
                "MO": "Macao",
                "MK": "Macedonia, the Former Yugoslav Republic of",
                "MG": "Madagascar",
                "MW": "Malawi",
                "MY": "Malaysia",
                "MV": "Maldives",
                "ML": "Mali",
                "MT": "Malta",
                "MH": "Marshall Islands",
                "MQ": "Martinique",
                "MR": "Mauritania",
                "MU": "Mauritius",
                "YT": "Mayotte",
                "MX": "Mexico",
                "FM": "Micronesia, Federated States of",
                "MD": "Moldova, Republic of",
                "MC": "Monaco",
                "MN": "Mongolia",
                "ME": "Montenegro",
                "MS": "Montserrat",
                "MA": "Morocco",
                "MZ": "Mozambique",
                "MM": "Myanmar",
                "NA": "Namibia",
                "NR": "Nauru",
                "NP": "Nepal",
                "NL": "Netherlands",
                "NC": "New Caledonia",
                "NZ": "New Zealand",
                "NI": "Nicaragua",
                "NE": "Niger",
                "NG": "Nigeria",
                "NU": "Niue",
                "NF": "Norfolk Island",
                "MP": "Northern Mariana Islands",
                "NO": "Norway",
                "OM": "Oman",
                "PK": "Pakistan",
                "PW": "Palau",
                "PS": "Palestine, State of",
                "PA": "Panama",
                "PG": "Papua New Guinea",
                "PY": "Paraguay",
                "PE": "Peru",
                "PH": "Philippines",
                "PN": "Pitcairn",
                "PL": "Poland",
                "PT": "Portugal",
                "PR": "Puerto Rico",
                "QA": "Qatar",
                "RE": "Réunion",
                "RO": "Romania",
                "RU": "Russian Federation",
                "RW": "Rwanda",
                "BL": "Saint Barthélemy",
                "SH": "Saint Helena, Ascension and Tristan da Cunha",
                "KN": "Saint Kitts and Nevis",
                "LC": "Saint Lucia",
                "MF": "Saint Martin (French part)",
                "PM": "Saint Pierre and Miquelon",
                "VC": "Saint Vincent and the Grenadines",
                "WS": "Samoa",
                "SM": "San Marino",
                "ST": "Sao Tome and Principe",
                "SA": "Saudi Arabia",
                "SN": "Senegal",
                "RS": "Serbia",
                "SC": "Seychelles",
                "SL": "Sierra Leone",
                "SG": "Singapore",
                "SX": "Sint Maarten (Dutch part)",
                "SK": "Slovakia",
                "SI": "Slovenia",
                "SB": "Solomon Islands",
                "SO": "Somalia",
                "ZA": "South Africa",
                "GS": "South Georgia and the South Sandwich Islands",
                "SS": "South Sudan",
                "ES": "Spain",
                "LK": "Sri Lanka",
                "SD": "Sudan",
                "SR": "Suriname",
                "SJ": "Svalbard and Jan Mayen",
                "SZ": "Swaziland",
                "SE": "Sweden",
                "SY": "Syrian Arab Republic",
                "TW": "Taiwan, Province of China",
                "TJ": "Tajikistan",
                "TZ": "Tanzania, United Republic of",
                "TH": "Thailand",
                "TL": "Timor-Leste",
                "TG": "Togo",
                "TK": "Tokelau",
                "TO": "Tonga",
                "TT": "Trinidad and Tobago",
                "TN": "Tunisia",
                "TR": "Turkey",
                "TM": "Turkmenistan",
                "TC": "Turks and Caicos Islands",
                "TV": "Tuvalu",
                "UG": "Uganda",
                "UA": "Ukraine",
                "AE": "United Arab Emirates",
                "GB": "United Kingdom",
                "US": "United States",
                "UM": "United States Minor Outlying Islands",
                "UY": "Uruguay",
                "UZ": "Uzbekistan",
                "VU": "Vanuatu",
                "VE": "Venezuela, Bolivarian Republic of",
                "VN": "Viet Nam",
                "VG": "Virgin Islands, British",
                "VI": "Virgin Islands, U.S.",
                "WF": "Wallis and Futuna",
                "EH": "Western Sahara",
                "YE": "Yemen",
                "ZM": "Zambia",
                "ZW": "Zimbabwe"
            },

            //Country codes for phone
            "#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div > div:nth-child(1) > div > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select": {
                "+41":"CH",
                "+33":"FR",
                "+93":"AF",
                "+355":"AL",
                "+213":"DZ",
                "+1-684":"AS",
                "+376":"AD",
                "+244":"AO",
                "+1-264":"AI",
                "+672":"AQ",
                "+1-268":"AG",
                "+54":"AR",
                "+374":"AM",
                "+297":"AW",
                "+61":"AU",
                "+43":"AT",
                "+994":"AZ",
                "+1-242":"BS",
                "+973":"BH",
                "+880":"BD",
                "+1-246":"BB",
                "+375":"BY",
                "+32":"BE",
                "+501":"BZ",
                "+229":"BJ",
                "+1-441":"BM",
                "+975":"BT",
                "+591":"BO",
                "+387":"BA",
                "+267":"BW",
                "+55":"BR",
                "+673":"BN",
                "+359":"BG",
                "+226":"BF",
                "+257":"BI",
                "+855":"KH",
                "+237":"CM",
                "+1":"CA/US",
                "+238":"CV",
                "+1-345":"KY",
                "+236":"CF",
                "+235":"TD",
                "+56":"CL",
                "+86":"CN",
                "+53":"CX",
                "+57":"CO",
                "+269":"KM",
                "+243":"CD",
                "+242":"CG",
                "+682":"CK",
                "+506":"CR",
                "+225":"CI",
                "+385":"HR",
                "+357":"CY",
                "+420":"CZ",
                "+45":"DK",
                "+253":"DJ",
                "+1-767":"DM",
                "+1-829":"DO",
                "+670":"TP",
                "+593 ":"EC",
                "+20":"EG",
                "+503":"SV",
                "+240":"GQ",
                "+291":"ER",
                "+372":"EE",
                "+251":"ET",
                "+500":"FK",
                "+298":"FO",
                "+679":"FJ",
                "+358":"FI",
                "+594":"GF",
                "+689":"PF",
                "+241":"GA",
                "+220":"GM",
                "+995":"GE",
                "+49":"DE",
                "+233":"GH",
                "+350":"GI",
                "+30":"GR",
                "+299":"GL",
                "+1-473":"GD",
                "+590":"GP",
                "+1-671":"GU",
                "+502":"GT",
                "+224":"GN",
                "+245":"GW",
                "+592":"GY",
                "+509":"HT",
                "+504":"HN",
                "+852":"HK",
                "+36":"HU",
                "+354":"IS",
                "+91":"IN",
                "+62":"ID",
                "+98":"IR",
                "+964":"IQ",
                "+353":"IE",
                "+972":"IL",
                "+39":"IT",
                "+1-876":"JM",
                "+81":"JP",
                "+962":"JO",
                "+7":"KZ",
                "+254":"KE",
                "+686":"KI",
                "+850":"KP",
                "+82":"KR",
                "+965":"KW",
                "+996":"KG",
                "+856":"LA",
                "+371":"LV",
                "+961":"LB",
                "+266":"LS",
                "+231":"LR",
                "+218":"LY",
                "+423":"LI",
                "+370":"LT",
                "+352":"LU",
                "+853":"MO",
                "+389":"MK",
                "+261":"MG",
                "+265":"MW",
                "+60":"MY",
                "+960":"MV",
                "+223":"ML",
                "+356":"MT",
                "+692":"MH",
                "+596":"MQ",
                "+222":"MR",
                "+230":"MU",
                "+52":"MX",
                "+691":"FM",
                "+373":"MD",
                "+377":"MC",
                "+976":"MN",
                "+1-664":"MS",
                "+212":"MA",
                "+258":"MZ",
                "+95":"MM",
                "+264":"NA",
                "+674":"NR",
                "+977":"NP",
                "+31":"NL",
                "+599":"AN",
                "+687":"NC",
                "+64":"NZ",
                "+505":"NI",
                "+227":"NE",
                "+234":"NG",
                "+683":"NU",
                "+1-670":"MP",
                "+47":"NO",
                "+968":"OM",
                "+92":"PK",
                "+680":"PW",
                "+970":"PS",
                "+507":"PA",
                "+675":"PG",
                "+595":"PY",
                "+51":"PE",
                "+63":"PH",
                "+48":"PL",
                "+351":"PT",
                "+1-939":"PR",
                "+974 ":"QA",
                "+262":"RE",
                "+40":"RO",
                "+250":"RW",
                "+290":"SH",
                "+1-869":"KN",
                "+1-758":"LC",
                "+508":"PM",
                "+1-784":"VC",
                "+685":"WS",
                "+378":"SM",
                "+239":"ST",
                "+966":"SA",
                "+381":"SN",
                "+221":"SN",
                "+248":"SC",
                "+232":"SL",
                "+65":"SG",
                "+421":"SK",
                "+386":"SI",
                "+677":"SB",
                "+252":"SO",
                "+27":"ZA",
                "+34":"ES",
                "+94":"LK",
                "+249":"SD",
                "+597":"SR",
                "+268":"SZ",
                "+46":"SE",
                "+963":"SY",
                "+886":"TW",
                "+992":"TJ",
                "+255":"TZ",
                "+66":"TH",
                "+690":"TK",
                "+676":"TO",
                "+1-868":"TT",
                "+216":"TN",
                "+90":"TR",
                "+993":"TM",
                "+1-649":"TC",
                "+688":"TV",
                "+256":"UG",
                "+380":"UA",
                "+971":"AE",
                "+44":"GB",
                "+598":"UY",
                "+998":"UZ",
                "+678":"VU",
                "+418":"VA",
                "+58":"VE",
                "+84":"VN",
                "+1-284":"VI",
                "+1-340":"VQ",
                "+681":"WF",
                "+967":"YE",
                "+260":"ZM",
                "+263":"ZW"
            },
            "#root > div > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div > div:nth-child(1) > div > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select"  : {
                "+41":"CH",
                "+33":"FR",
                "+93":"AF",
                "+355":"AL",
                "+213":"DZ",
                "+1-684":"AS",
                "+376":"AD",
                "+244":"AO",
                "+1-264":"AI",
                "+672":"AQ",
                "+1-268":"AG",
                "+54":"AR",
                "+374":"AM",
                "+297":"AW",
                "+61":"AU",
                "+43":"AT",
                "+994":"AZ",
                "+1-242":"BS",
                "+973":"BH",
                "+880":"BD",
                "+1-246":"BB",
                "+375":"BY",
                "+32":"BE",
                "+501":"BZ",
                "+229":"BJ",
                "+1-441":"BM",
                "+975":"BT",
                "+591":"BO",
                "+387":"BA",
                "+267":"BW",
                "+55":"BR",
                "+673":"BN",
                "+359":"BG",
                "+226":"BF",
                "+257":"BI",
                "+855":"KH",
                "+237":"CM",
                "+1":"CA/US",
                "+238":"CV",
                "+1-345":"KY",
                "+236":"CF",
                "+235":"TD",
                "+56":"CL",
                "+86":"CN",
                "+53":"CX",
                "+57":"CO",
                "+269":"KM",
                "+243":"CD",
                "+242":"CG",
                "+682":"CK",
                "+506":"CR",
                "+225":"CI",
                "+385":"HR",
                "+357":"CY",
                "+420":"CZ",
                "+45":"DK",
                "+253":"DJ",
                "+1-767":"DM",
                "+1-829":"DO",
                "+670":"TP",
                "+593 ":"EC",
                "+20":"EG",
                "+503":"SV",
                "+240":"GQ",
                "+291":"ER",
                "+372":"EE",
                "+251":"ET",
                "+500":"FK",
                "+298":"FO",
                "+679":"FJ",
                "+358":"FI",
                "+594":"GF",
                "+689":"PF",
                "+241":"GA",
                "+220":"GM",
                "+995":"GE",
                "+49":"DE",
                "+233":"GH",
                "+350":"GI",
                "+30":"GR",
                "+299":"GL",
                "+1-473":"GD",
                "+590":"GP",
                "+1-671":"GU",
                "+502":"GT",
                "+224":"GN",
                "+245":"GW",
                "+592":"GY",
                "+509":"HT",
                "+504":"HN",
                "+852":"HK",
                "+36":"HU",
                "+354":"IS",
                "+91":"IN",
                "+62":"ID",
                "+98":"IR",
                "+964":"IQ",
                "+353":"IE",
                "+972":"IL",
                "+39":"IT",
                "+1-876":"JM",
                "+81":"JP",
                "+962":"JO",
                "+7":"KZ",
                "+254":"KE",
                "+686":"KI",
                "+850":"KP",
                "+82":"KR",
                "+965":"KW",
                "+996":"KG",
                "+856":"LA",
                "+371":"LV",
                "+961":"LB",
                "+266":"LS",
                "+231":"LR",
                "+218":"LY",
                "+423":"LI",
                "+370":"LT",
                "+352":"LU",
                "+853":"MO",
                "+389":"MK",
                "+261":"MG",
                "+265":"MW",
                "+60":"MY",
                "+960":"MV",
                "+223":"ML",
                "+356":"MT",
                "+692":"MH",
                "+596":"MQ",
                "+222":"MR",
                "+230":"MU",
                "+52":"MX",
                "+691":"FM",
                "+373":"MD",
                "+377":"MC",
                "+976":"MN",
                "+1-664":"MS",
                "+212":"MA",
                "+258":"MZ",
                "+95":"MM",
                "+264":"NA",
                "+674":"NR",
                "+977":"NP",
                "+31":"NL",
                "+599":"AN",
                "+687":"NC",
                "+64":"NZ",
                "+505":"NI",
                "+227":"NE",
                "+234":"NG",
                "+683":"NU",
                "+1-670":"MP",
                "+47":"NO",
                "+968":"OM",
                "+92":"PK",
                "+680":"PW",
                "+970":"PS",
                "+507":"PA",
                "+675":"PG",
                "+595":"PY",
                "+51":"PE",
                "+63":"PH",
                "+48":"PL",
                "+351":"PT",
                "+1-939":"PR",
                "+974 ":"QA",
                "+262":"RE",
                "+40":"RO",
                "+250":"RW",
                "+290":"SH",
                "+1-869":"KN",
                "+1-758":"LC",
                "+508":"PM",
                "+1-784":"VC",
                "+685":"WS",
                "+378":"SM",
                "+239":"ST",
                "+966":"SA",
                "+381":"SN",
                "+221":"SN",
                "+248":"SC",
                "+232":"SL",
                "+65":"SG",
                "+421":"SK",
                "+386":"SI",
                "+677":"SB",
                "+252":"SO",
                "+27":"ZA",
                "+34":"ES",
                "+94":"LK",
                "+249":"SD",
                "+597":"SR",
                "+268":"SZ",
                "+46":"SE",
                "+963":"SY",
                "+886":"TW",
                "+992":"TJ",
                "+255":"TZ",
                "+66":"TH",
                "+690":"TK",
                "+676":"TO",
                "+1-868":"TT",
                "+216":"TN",
                "+90":"TR",
                "+993":"TM",
                "+1-649":"TC",
                "+688":"TV",
                "+256":"UG",
                "+380":"UA",
                "+971":"AE",
                "+44":"GB",
                "+598":"UY",
                "+998":"UZ",
                "+678":"VU",
                "+418":"VA",
                "+58":"VE",
                "+84":"VN",
                "+1-284":"VI",
                "+1-340":"VQ",
                "+681":"WF",
                "+967":"YE",
                "+260":"ZM",
                "+263":"ZW"
            }
        }
    },
}


//export { standardConvertionTable, standardFields, standardLists, defaultFormFields, defaultQrOptions };


/*            //Country
            "#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div.columns.pt-4 > div:nth-child(2) > div:nth-child(5) > div.control.has-icons-left > div > select": {
                "CH": "Switzerland",
                "FR": "France",
                "IT": "Italy",
                "AT": "Austria",
                "AF": "Afghanistan",
                "AX": "Åland Islands",
                "AL": "Albania",
                "DZ": "Algeria",
                "AS": "American Samoa",
                "AD": "Andorra",
                "AO": "Angola",
                "AI": "Anguilla",
                "AQ": "Antarctica",
                "AG": "Antigua and Barbuda",
                "AR": "Argentina",
                "AM": "Armenia",
                "AW": "Aruba",
                "AU": "Australia",
                "AZ": "Azerbaijan",
                "BS": "Bahamas",
                "BH": "Bahrain",
                "BD": "Bangladesh",
                "BB": "Barbados",
                "BY": "Belarus",
                "BE": "Belgium",
                "BZ": "Belize",
                "BJ": "Benin",
                "BM": "Bermuda",
                "BT": "Bhutan",
                "BO": "Bolivia, Plurinational State of",
                "BQ": "Bonaire, Sint Eustatius and Saba",
                "BA": "Bosnia and Herzegovina",
                "BW": "Botswana",
                "BV": "Bouvet Island",
                "BR": "Brazil",
                "IO": "British Indian Ocean Territory",
                "BN": "Brunei Darussalam",
                "BG": "Bulgaria",
                "BF": "Burkina Faso",
                "BI": "Burundi",
                "KH": "Cambodia",
                "CM": "Cameroon",
                "CA": "Canada",
                "CV": "Cape Verde",
                "KY": "Cayman Islands",
                "CF": "Central African Republic",
                "TD": "Chad",
                "CL": "Chile",
                "CN": "China",
                "CX": "Christmas Island",
                "CC": "Cocos (Keeling) Islands",
                "CO": "Colombia",
                "KM": "Comoros",
                "CG": "Congo",
                "CD": "Congo, the Democratic Republic of the",
                "CK": "Cook Islands",
                "CR": "Costa Rica",
                "CI": "Côte d'Ivoire",
                "HR": "Croatia",
                "CU": "Cuba",
                "CW": "Curaçao",
                "CY": "Cyprus",
                "CZ": "Czech Republic",
                "DK": "Denmark",
                "DJ": "Djibouti",
                "DM": "Dominica",
                "DO": "Dominican Republic",
                "EC": "Ecuador",
                "EG": "Egypt",
                "SV": "El Salvador",
                "GQ": "Equatorial Guinea",
                "ER": "Eritrea",
                "EE": "Estonia",
                "ET": "Ethiopia",
                "FK": "Falkland Islands (Malvinas)",
                "FO": "Faroe Islands",
                "FJ": "Fiji",
                "FI": "Finland",
                "GF": "French Guiana",
                "PF": "French Polynesia",
                "TF": "French Southern Territories",
                "GA": "Gabon",
                "GM": "Gambia",
                "GE": "Georgia",
                "DE": "Germany",
                "GH": "Ghana",
                "GI": "Gibraltar",
                "GR": "Greece",
                "GL": "Greenland",
                "GD": "Grenada",
                "GP": "Guadeloupe",
                "GU": "Guam",
                "GT": "Guatemala",
                "GG": "Guernsey",
                "GN": "Guinea",
                "GW": "Guinea-Bissau",
                "GY": "Guyana",
                "HT": "Haiti",
                "HM": "Heard Island and McDonald Mcdonald Islands",
                "VA": "Holy See (Vatican City State)",
                "HN": "Honduras",
                "HK": "Hong Kong",
                "HU": "Hungary",
                "IS": "Iceland",
                "IN": "India",
                "ID": "Indonesia",
                "IR": "Iran, Islamic Republic of",
                "IQ": "Iraq",
                "IE": "Ireland",
                "IM": "Isle of Man",
                "IL": "Israel",
                "JM": "Jamaica",
                "JP": "Japan",
                "JE": "Jersey",
                "JO": "Jordan",
                "KZ": "Kazakhstan",
                "KE": "Kenya",
                "KI": "Kiribati",
                "KP": "Korea, Democratic People's Republic of",
                "KR": "Korea, Republic of",
                "KW": "Kuwait",
                "KG": "Kyrgyzstan",
                "LA": "Lao People's Democratic Republic",
                "LV": "Latvia",
                "LB": "Lebanon",
                "LS": "Lesotho",
                "LR": "Liberia",
                "LY": "Libya",
                "LI": "Liechtenstein",
                "LT": "Lithuania",
                "LU": "Luxembourg",
                "MO": "Macao",
                "MK": "Macedonia, the Former Yugoslav Republic of",
                "MG": "Madagascar",
                "MW": "Malawi",
                "MY": "Malaysia",
                "MV": "Maldives",
                "ML": "Mali",
                "MT": "Malta",
                "MH": "Marshall Islands",
                "MQ": "Martinique",
                "MR": "Mauritania",
                "MU": "Mauritius",
                "YT": "Mayotte",
                "MX": "Mexico",
                "FM": "Micronesia, Federated States of",
                "MD": "Moldova, Republic of",
                "MC": "Monaco",
                "MN": "Mongolia",
                "ME": "Montenegro",
                "MS": "Montserrat",
                "MA": "Morocco",
                "MZ": "Mozambique",
                "MM": "Myanmar",
                "NA": "Namibia",
                "NR": "Nauru",
                "NP": "Nepal",
                "NL": "Netherlands",
                "NC": "New Caledonia",
                "NZ": "New Zealand",
                "NI": "Nicaragua",
                "NE": "Niger",
                "NG": "Nigeria",
                "NU": "Niue",
                "NF": "Norfolk Island",
                "MP": "Northern Mariana Islands",
                "NO": "Norway",
                "OM": "Oman",
                "PK": "Pakistan",
                "PW": "Palau",
                "PS": "Palestine, State of",
                "PA": "Panama",
                "PG": "Papua New Guinea",
                "PY": "Paraguay",
                "PE": "Peru",
                "PH": "Philippines",
                "PN": "Pitcairn",
                "PL": "Poland",
                "PT": "Portugal",
                "PR": "Puerto Rico",
                "QA": "Qatar",
                "RE": "Réunion",
                "RO": "Romania",
                "RU": "Russian Federation",
                "RW": "Rwanda",
                "BL": "Saint Barthélemy",
                "SH": "Saint Helena, Ascension and Tristan da Cunha",
                "KN": "Saint Kitts and Nevis",
                "LC": "Saint Lucia",
                "MF": "Saint Martin (French part)",
                "PM": "Saint Pierre and Miquelon",
                "VC": "Saint Vincent and the Grenadines",
                "WS": "Samoa",
                "SM": "San Marino",
                "ST": "Sao Tome and Principe",
                "SA": "Saudi Arabia",
                "SN": "Senegal",
                "RS": "Serbia",
                "SC": "Seychelles",
                "SL": "Sierra Leone",
                "SG": "Singapore",
                "SX": "Sint Maarten (Dutch part)",
                "SK": "Slovakia",
                "SI": "Slovenia",
                "SB": "Solomon Islands",
                "SO": "Somalia",
                "ZA": "South Africa",
                "GS": "South Georgia and the South Sandwich Islands",
                "SS": "South Sudan",
                "ES": "Spain",
                "LK": "Sri Lanka",
                "SD": "Sudan",
                "SR": "Suriname",
                "SJ": "Svalbard and Jan Mayen",
                "SZ": "Swaziland",
                "SE": "Sweden",
                "SY": "Syrian Arab Republic",
                "TW": "Taiwan, Province of China",
                "TJ": "Tajikistan",
                "TZ": "Tanzania, United Republic of",
                "TH": "Thailand",
                "TL": "Timor-Leste",
                "TG": "Togo",
                "TK": "Tokelau",
                "TO": "Tonga",
                "TT": "Trinidad and Tobago",
                "TN": "Tunisia",
                "TR": "Turkey",
                "TM": "Turkmenistan",
                "TC": "Turks and Caicos Islands",
                "TV": "Tuvalu",
                "UG": "Uganda",
                "UA": "Ukraine",
                "AE": "United Arab Emirates",
                "GB": "United Kingdom",
                "US": "United States",
                "UM": "United States Minor Outlying Islands",
                "UY": "Uruguay",
                "UZ": "Uzbekistan",
                "VU": "Vanuatu",
                "VE": "Venezuela, Bolivarian Republic of",
                "VN": "Viet Nam",
                "VG": "Virgin Islands, British",
                "VI": "Virgin Islands, U.S.",
                "WF": "Wallis and Futuna",
                "EH": "Western Sahara",
                "YE": "Yemen",
                "ZM": "Zambia",
                "ZW": "Zimbabwe"
            },//Country codes for phone
            "#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div.columns.pt-4 > div:nth-child(1) > div:nth-child(7) > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select" : {
                "+41":"CH",
                "+33":"FR",
                "+93":"AF",
                "+355":"AL",
                "+213":"DZ",
                "+1-684":"AS",
                "+376":"AD",
                "+244":"AO",
                "+1-264":"AI",
                "+672":"AQ",
                "+1-268":"AG",
                "+54":"AR",
                "+374":"AM",
                "+297":"AW",
                "+61":"AU",
                "+43":"AT",
                "+994":"AZ",
                "+1-242":"BS",
                "+973":"BH",
                "+880":"BD",
                "+1-246":"BB",
                "+375":"BY",
                "+32":"BE",
                "+501":"BZ",
                "+229":"BJ",
                "+1-441":"BM",
                "+975":"BT",
                "+591":"BO",
                "+387":"BA",
                "+267":"BW",
                "+55":"BR",
                "+673":"BN",
                "+359":"BG",
                "+226":"BF",
                "+257":"BI",
                "+855":"KH",
                "+237":"CM",
                "+1":"CA",
                "+238":"CV",
                "+1-345":"KY",
                "+236":"CF",
                "+235":"TD",
                "+56":"CL",
                "+86":"CN",
                "+53":"CX",
                "+61":"CC",
                "+57":"CO",
                "+269":"KM",
                "+243":"CD",
                "+242":"CG",
                "+682":"CK",
                "+506":"CR",
                "+225":"CI",
                "+385":"HR",
                "+53":"CU",
                "+357":"CY",
                "+420":"CZ",
                "+45":"DK",
                "+253":"DJ",
                "+1-767":"DM",
                "+1-829":"DO",
                "+670":"TP",
                "+593 ":"EC",
                "+20":"EG",
                "+503":"SV",
                "+240":"GQ",
                "+291":"ER",
                "+372":"EE",
                "+251":"ET",
                "+500":"FK",
                "+298":"FO",
                "+679":"FJ",
                "+358":"FI",
                "+594":"GF",
                "+689":"PF",
                "+241":"GA",
                "+220":"GM",
                "+995":"GE",
                "+49":"DE",
                "+233":"GH",
                "+350":"GI",
                "+30":"GR",
                "+299":"GL",
                "+1-473":"GD",
                "+590":"GP",
                "+1-671":"GU",
                "+502":"GT",
                "+224":"GN",
                "+245":"GW",
                "+592":"GY",
                "+509":"HT",
                "+504":"HN",
                "+852":"HK",
                "+36":"HU",
                "+354":"IS",
                "+91":"IN",
                "+62":"ID",
                "+98":"IR",
                "+964":"IQ",
                "+353":"IE",
                "+972":"IL",
                "+39":"IT",
                "+1-876":"JM",
                "+81":"JP",
                "+962":"JO",
                "+7":"KZ",
                "+254":"KE",
                "+686":"KI",
                "+850":"KP",
                "+82":"KR",
                "+965":"KW",
                "+996":"KG",
                "+856":"LA",
                "+371":"LV",
                "+961":"LB",
                "+266":"LS",
                "+231":"LR",
                "+218":"LY",
                "+423":"LI",
                "+370":"LT",
                "+352":"LU",
                "+853":"MO",
                "+389":"MK",
                "+261":"MG",
                "+265":"MW",
                "+60":"MY",
                "+960":"MV",
                "+223":"ML",
                "+356":"MT",
                "+692":"MH",
                "+596":"MQ",
                "+222":"MR",
                "+230":"MU",
                "+269":"YT",
                "+52":"MX",
                "+691":"FM",
                "+373":"MD",
                "+377":"MC",
                "+976":"MN",
                "+1-664":"MS",
                "+212":"MA",
                "+258":"MZ",
                "+95":"MM",
                "+264":"NA",
                "+674":"NR",
                "+977":"NP",
                "+31":"NL",
                "+599":"AN",
                "+687":"NC",
                "+64":"NZ",
                "+505":"NI",
                "+227":"NE",
                "+234":"NG",
                "+683":"NU",
                "+672":"NF",
                "+1-670":"MP",
                "+47":"NO",
                "+968":"OM",
                "+92":"PK",
                "+680":"PW",
                "+970":"PS",
                "+507":"PA",
                "+675":"PG",
                "+595":"PY",
                "+51":"PE",
                "+63":"PH",
                "+48":"PL",
                "+351":"PT",
                "+1-939":"PR",
                "+974 ":"QA",
                "+262":"RE",
                "+40":"RO",
                "+7":"RU",
                "+250":"RW",
                "+290":"SH",
                "+1-869":"KN",
                "+1-758":"LC",
                "+508":"PM",
                "+1-784":"VC",
                "+685":"WS",
                "+378":"SM",
                "+239":"ST",
                "+966":"SA",
                "+381":"SN",
                "+221":"SN",
                "+248":"SC",
                "+232":"SL",
                "+65":"SG",
                "+421":"SK",
                "+386":"SI",
                "+677":"SB",
                "+252":"SO",
                "+27":"ZA",
                "+34":"ES",
                "+94":"LK",
                "+249":"SD",
                "+597":"SR",
                "+268":"SZ",
                "+46":"SE",
                "+963":"SY",
                "+886":"TW",
                "+992":"TJ",
                "+255":"TZ",
                "+66":"TH",
                "+690":"TK",
                "+676":"TO",
                "+1-868":"TT",
                "+216":"TN",
                "+90":"TR",
                "+993":"TM",
                "+1-649":"TC",
                "+688":"TV",
                "+256":"UG",
                "+380":"UA",
                "+971":"AE",
                "+44":"GB",
                "+1":"US",
                "+598":"UY",
                "+998":"UZ",
                "+678":"VU",
                "+418":"VA",
                "+58":"VE",
                "+84":"VN",
                "+1-284":"VI",
                "+1-340":"VQ",
                "+681":"WF",
                "+967":"YE",
                "+260":"ZM",
                "+263":"ZW"






            }
*/



/*
    ,
    "https?:\/\/.*\.m3-test\.ch\/admin\/platform\/team":{
        dataLocations: { // Associate inputs with elemenents in formData.payload
            "input[autocomplete='firstname']": ["form", "firstname"],
            "input[autocomplete='lastname']": ["form", "lastname"],
            //"#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div:nth-child(4) > div:nth-child(1) > div:nth-child(5) > div.control.has-icons-left > div > div.react-datepicker-wrapper > div > input": ["form", "birthdate"],
            "div.react-datepicker-wrapper > div > input": ["form", "birthdate"],
            "input[autocomplete='email']": ["form", "email"],
            "input[autocomplete='phone']": ["form", "mobile"],
            "input[autocomplete='address line 1']": ["form", "address1"],
            "input[autocomplete='address line 2']": ["form", "address2"],
            "input[autocomplete='postal code']": ["form", "postcode"],
            "input[autocomplete='city']": ["form", "city"],
            //"#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div:nth-child(4) > div:nth-child(2) > div:nth-child(5) > div.control.has-icons-left > div > select": ["form", "country"],
            "#root > div:nth-child(3) > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div:nth-child(4) > div:nth-child(2) > div:nth-child(6) > div.control.has-icons-left > div > select": ["form", "country"],
            "input[id='maleRadio']": ["form", "sex"],
            "input[id='femaleRadio']": ["form", "sex"],
            //"#root > div.wrapper > div > section > div > div > section.booking-funnel-step.section.pt-3 > div > div:nth-child(4) > div:nth-child(1) > div:nth-child(7) > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select": ["form", "countrycode"]
            "#root > div:nth-child(3) > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div:nth-child(4) > div:nth-child(1) > div:nth-child(8) > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select": ["form", "countrycode"]
        },
        dataTransforms: { // Modify the value of specified inputs based on below transformation tables
            "input[id='maleRadio']": {
                "male": true,
                "female": false
            },
            "input[id='femaleRadio']": {
                "male": false,
                "female": true
            },
            //Country
            "#root > div:nth-child(3) > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div:nth-child(4) > div:nth-child(2) > div:nth-child(6) > div.control.has-icons-left > div > select": {
                "CH": "Switzerland",
                "FR": "France",
                "IT": "Italy",
                "AT": "Austria",
                "AF": "Afghanistan",
                "AX": "Åland Islands",
                "AL": "Albania",
                "DZ": "Algeria",
                "AS": "American Samoa",
                "AD": "Andorra",
                "AO": "Angola",
                "AI": "Anguilla",
                "AQ": "Antarctica",
                "AG": "Antigua and Barbuda",
                "AR": "Argentina",
                "AM": "Armenia",
                "AW": "Aruba",
                "AU": "Australia",
                "AZ": "Azerbaijan",
                "BS": "Bahamas",
                "BH": "Bahrain",
                "BD": "Bangladesh",
                "BB": "Barbados",
                "BY": "Belarus",
                "BE": "Belgium",
                "BZ": "Belize",
                "BJ": "Benin",
                "BM": "Bermuda",
                "BT": "Bhutan",
                "BO": "Bolivia, Plurinational State of",
                "BQ": "Bonaire, Sint Eustatius and Saba",
                "BA": "Bosnia and Herzegovina",
                "BW": "Botswana",
                "BV": "Bouvet Island",
                "BR": "Brazil",
                "IO": "British Indian Ocean Territory",
                "BN": "Brunei Darussalam",
                "BG": "Bulgaria",
                "BF": "Burkina Faso",
                "BI": "Burundi",
                "KH": "Cambodia",
                "CM": "Cameroon",
                "CA": "Canada",
                "CV": "Cape Verde",
                "KY": "Cayman Islands",
                "CF": "Central African Republic",
                "TD": "Chad",
                "CL": "Chile",
                "CN": "China",
                "CX": "Christmas Island",
                "CC": "Cocos (Keeling) Islands",
                "CO": "Colombia",
                "KM": "Comoros",
                "CG": "Congo",
                "CD": "Congo, the Democratic Republic of the",
                "CK": "Cook Islands",
                "CR": "Costa Rica",
                "CI": "Côte d'Ivoire",
                "HR": "Croatia",
                "CU": "Cuba",
                "CW": "Curaçao",
                "CY": "Cyprus",
                "CZ": "Czech Republic",
                "DK": "Denmark",
                "DJ": "Djibouti",
                "DM": "Dominica",
                "DO": "Dominican Republic",
                "EC": "Ecuador",
                "EG": "Egypt",
                "SV": "El Salvador",
                "GQ": "Equatorial Guinea",
                "ER": "Eritrea",
                "EE": "Estonia",
                "ET": "Ethiopia",
                "FK": "Falkland Islands (Malvinas)",
                "FO": "Faroe Islands",
                "FJ": "Fiji",
                "FI": "Finland",
                "GF": "French Guiana",
                "PF": "French Polynesia",
                "TF": "French Southern Territories",
                "GA": "Gabon",
                "GM": "Gambia",
                "GE": "Georgia",
                "DE": "Germany",
                "GH": "Ghana",
                "GI": "Gibraltar",
                "GR": "Greece",
                "GL": "Greenland",
                "GD": "Grenada",
                "GP": "Guadeloupe",
                "GU": "Guam",
                "GT": "Guatemala",
                "GG": "Guernsey",
                "GN": "Guinea",
                "GW": "Guinea-Bissau",
                "GY": "Guyana",
                "HT": "Haiti",
                "HM": "Heard Island and McDonald Mcdonald Islands",
                "VA": "Holy See (Vatican City State)",
                "HN": "Honduras",
                "HK": "Hong Kong",
                "HU": "Hungary",
                "IS": "Iceland",
                "IN": "India",
                "ID": "Indonesia",
                "IR": "Iran, Islamic Republic of",
                "IQ": "Iraq",
                "IE": "Ireland",
                "IM": "Isle of Man",
                "IL": "Israel",
                "JM": "Jamaica",
                "JP": "Japan",
                "JE": "Jersey",
                "JO": "Jordan",
                "KZ": "Kazakhstan",
                "KE": "Kenya",
                "KI": "Kiribati",
                "KP": "Korea, Democratic People's Republic of",
                "KR": "Korea, Republic of",
                "KW": "Kuwait",
                "KG": "Kyrgyzstan",
                "LA": "Lao People's Democratic Republic",
                "LV": "Latvia",
                "LB": "Lebanon",
                "LS": "Lesotho",
                "LR": "Liberia",
                "LY": "Libya",
                "LI": "Liechtenstein",
                "LT": "Lithuania",
                "LU": "Luxembourg",
                "MO": "Macao",
                "MK": "Macedonia, the Former Yugoslav Republic of",
                "MG": "Madagascar",
                "MW": "Malawi",
                "MY": "Malaysia",
                "MV": "Maldives",
                "ML": "Mali",
                "MT": "Malta",
                "MH": "Marshall Islands",
                "MQ": "Martinique",
                "MR": "Mauritania",
                "MU": "Mauritius",
                "YT": "Mayotte",
                "MX": "Mexico",
                "FM": "Micronesia, Federated States of",
                "MD": "Moldova, Republic of",
                "MC": "Monaco",
                "MN": "Mongolia",
                "ME": "Montenegro",
                "MS": "Montserrat",
                "MA": "Morocco",
                "MZ": "Mozambique",
                "MM": "Myanmar",
                "NA": "Namibia",
                "NR": "Nauru",
                "NP": "Nepal",
                "NL": "Netherlands",
                "NC": "New Caledonia",
                "NZ": "New Zealand",
                "NI": "Nicaragua",
                "NE": "Niger",
                "NG": "Nigeria",
                "NU": "Niue",
                "NF": "Norfolk Island",
                "MP": "Northern Mariana Islands",
                "NO": "Norway",
                "OM": "Oman",
                "PK": "Pakistan",
                "PW": "Palau",
                "PS": "Palestine, State of",
                "PA": "Panama",
                "PG": "Papua New Guinea",
                "PY": "Paraguay",
                "PE": "Peru",
                "PH": "Philippines",
                "PN": "Pitcairn",
                "PL": "Poland",
                "PT": "Portugal",
                "PR": "Puerto Rico",
                "QA": "Qatar",
                "RE": "Réunion",
                "RO": "Romania",
                "RU": "Russian Federation",
                "RW": "Rwanda",
                "BL": "Saint Barthélemy",
                "SH": "Saint Helena, Ascension and Tristan da Cunha",
                "KN": "Saint Kitts and Nevis",
                "LC": "Saint Lucia",
                "MF": "Saint Martin (French part)",
                "PM": "Saint Pierre and Miquelon",
                "VC": "Saint Vincent and the Grenadines",
                "WS": "Samoa",
                "SM": "San Marino",
                "ST": "Sao Tome and Principe",
                "SA": "Saudi Arabia",
                "SN": "Senegal",
                "RS": "Serbia",
                "SC": "Seychelles",
                "SL": "Sierra Leone",
                "SG": "Singapore",
                "SX": "Sint Maarten (Dutch part)",
                "SK": "Slovakia",
                "SI": "Slovenia",
                "SB": "Solomon Islands",
                "SO": "Somalia",
                "ZA": "South Africa",
                "GS": "South Georgia and the South Sandwich Islands",
                "SS": "South Sudan",
                "ES": "Spain",
                "LK": "Sri Lanka",
                "SD": "Sudan",
                "SR": "Suriname",
                "SJ": "Svalbard and Jan Mayen",
                "SZ": "Swaziland",
                "SE": "Sweden",
                "SY": "Syrian Arab Republic",
                "TW": "Taiwan, Province of China",
                "TJ": "Tajikistan",
                "TZ": "Tanzania, United Republic of",
                "TH": "Thailand",
                "TL": "Timor-Leste",
                "TG": "Togo",
                "TK": "Tokelau",
                "TO": "Tonga",
                "TT": "Trinidad and Tobago",
                "TN": "Tunisia",
                "TR": "Turkey",
                "TM": "Turkmenistan",
                "TC": "Turks and Caicos Islands",
                "TV": "Tuvalu",
                "UG": "Uganda",
                "UA": "Ukraine",
                "AE": "United Arab Emirates",
                "GB": "United Kingdom",
                "US": "United States",
                "UM": "United States Minor Outlying Islands",
                "UY": "Uruguay",
                "UZ": "Uzbekistan",
                "VU": "Vanuatu",
                "VE": "Venezuela, Bolivarian Republic of",
                "VN": "Viet Nam",
                "VG": "Virgin Islands, British",
                "VI": "Virgin Islands, U.S.",
                "WF": "Wallis and Futuna",
                "EH": "Western Sahara",
                "YE": "Yemen",
                "ZM": "Zambia",
                "ZW": "Zimbabwe"
            },//Country codes for phone
            "#root > div:nth-child(3) > div > div > section > div > div > div.column.is-three-quarters.content-box > div > div > div > div > div.tile.is-parent.false > article > div > div > div:nth-child(4) > div:nth-child(1) > div:nth-child(8) > div.phone-container.columns > div.field.code.column.is-half > div > div.select.is-rounded > select" : {
                "+41":"CH",
                "+33":"FR",
                "+93":"AF",
                "+355":"AL",
                "+213":"DZ",
                "+1-684":"AS",
                "+376":"AD",
                "+244":"AO",
                "+1-264":"AI",
                "+672":"AQ",
                "+1-268":"AG",
                "+54":"AR",
                "+374":"AM",
                "+297":"AW",
                "+61":"AU",
                "+43":"AT",
                "+994":"AZ",
                "+1-242":"BS",
                "+973":"BH",
                "+880":"BD",
                "+1-246":"BB",
                "+375":"BY",
                "+32":"BE",
                "+501":"BZ",
                "+229":"BJ",
                "+1-441":"BM",
                "+975":"BT",
                "+591":"BO",
                "+387":"BA",
                "+267":"BW",
                "+55":"BR",
                "+673":"BN",
                "+359":"BG",
                "+226":"BF",
                "+257":"BI",
                "+855":"KH",
                "+237":"CM",
                "+1":"CA",
                "+238":"CV",
                "+1-345":"KY",
                "+236":"CF",
                "+235":"TD",
                "+56":"CL",
                "+86":"CN",
                "+53":"CX",
                "+61":"CC",
                "+57":"CO",
                "+269":"KM",
                "+243":"CD",
                "+242":"CG",
                "+682":"CK",
                "+506":"CR",
                "+225":"CI",
                "+385":"HR",
                "+53":"CU",
                "+357":"CY",
                "+420":"CZ",
                "+45":"DK",
                "+253":"DJ",
                "+1-767":"DM",
                "+1-829":"DO",
                "+670":"TP",
                "+593 ":"EC",
                "+20":"EG",
                "+503":"SV",
                "+240":"GQ",
                "+291":"ER",
                "+372":"EE",
                "+251":"ET",
                "+500":"FK",
                "+298":"FO",
                "+679":"FJ",
                "+358":"FI",
                "+594":"GF",
                "+689":"PF",
                "+241":"GA",
                "+220":"GM",
                "+995":"GE",
                "+49":"DE",
                "+233":"GH",
                "+350":"GI",
                "+30":"GR",
                "+299":"GL",
                "+1-473":"GD",
                "+590":"GP",
                "+1-671":"GU",
                "+502":"GT",
                "+224":"GN",
                "+245":"GW",
                "+592":"GY",
                "+509":"HT",
                "+504":"HN",
                "+852":"HK",
                "+36":"HU",
                "+354":"IS",
                "+91":"IN",
                "+62":"ID",
                "+98":"IR",
                "+964":"IQ",
                "+353":"IE",
                "+972":"IL",
                "+39":"IT",
                "+1-876":"JM",
                "+81":"JP",
                "+962":"JO",
                "+7":"KZ",
                "+254":"KE",
                "+686":"KI",
                "+850":"KP",
                "+82":"KR",
                "+965":"KW",
                "+996":"KG",
                "+856":"LA",
                "+371":"LV",
                "+961":"LB",
                "+266":"LS",
                "+231":"LR",
                "+218":"LY",
                "+423":"LI",
                "+370":"LT",
                "+352":"LU",
                "+853":"MO",
                "+389":"MK",
                "+261":"MG",
                "+265":"MW",
                "+60":"MY",
                "+960":"MV",
                "+223":"ML",
                "+356":"MT",
                "+692":"MH",
                "+596":"MQ",
                "+222":"MR",
                "+230":"MU",
                "+269":"YT",
                "+52":"MX",
                "+691":"FM",
                "+373":"MD",
                "+377":"MC",
                "+976":"MN",
                "+1-664":"MS",
                "+212":"MA",
                "+258":"MZ",
                "+95":"MM",
                "+264":"NA",
                "+674":"NR",
                "+977":"NP",
                "+31":"NL",
                "+599":"AN",
                "+687":"NC",
                "+64":"NZ",
                "+505":"NI",
                "+227":"NE",
                "+234":"NG",
                "+683":"NU",
                "+672":"NF",
                "+1-670":"MP",
                "+47":"NO",
                "+968":"OM",
                "+92":"PK",
                "+680":"PW",
                "+970":"PS",
                "+507":"PA",
                "+675":"PG",
                "+595":"PY",
                "+51":"PE",
                "+63":"PH",
                "+48":"PL",
                "+351":"PT",
                "+1-939":"PR",
                "+974 ":"QA",
                "+262":"RE",
                "+40":"RO",
                "+7":"RU",
                "+250":"RW",
                "+290":"SH",
                "+1-869":"KN",
                "+1-758":"LC",
                "+508":"PM",
                "+1-784":"VC",
                "+685":"WS",
                "+378":"SM",
                "+239":"ST",
                "+966":"SA",
                "+381":"SN",
                "+221":"SN",
                "+248":"SC",
                "+232":"SL",
                "+65":"SG",
                "+421":"SK",
                "+386":"SI",
                "+677":"SB",
                "+252":"SO",
                "+27":"ZA",
                "+34":"ES",
                "+94":"LK",
                "+249":"SD",
                "+597":"SR",
                "+268":"SZ",
                "+46":"SE",
                "+963":"SY",
                "+886":"TW",
                "+992":"TJ",
                "+255":"TZ",
                "+66":"TH",
                "+690":"TK",
                "+676":"TO",
                "+1-868":"TT",
                "+216":"TN",
                "+90":"TR",
                "+993":"TM",
                "+1-649":"TC",
                "+688":"TV",
                "+256":"UG",
                "+380":"UA",
                "+971":"AE",
                "+44":"GB",
                "+1":"US",
                "+598":"UY",
                "+998":"UZ",
                "+678":"VU",
                "+418":"VA",
                "+58":"VE",
                "+84":"VN",
                "+1-284":"VI",
                "+1-340":"VQ",
                "+681":"WF",
                "+967":"YE",
                "+260":"ZM",
                "+263":"ZW"
            }
        }
    }
}

*/